config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users
  root 'home#index'

  resources :chat_rooms, only: [:new, :create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  def name
    email.split('@')[0]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end
end

app/views/chat_rooms/_chat_room.html.slim
li
  = link_to "Enter #{chat_room.title}", chat_room_path(chat_room)

app/views/chat_rooms/index.html.slim
h1 Chat Rooms

p.lead= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary'

ul
  = render @chat_rooms

app/views/chat_rooms/new.html.slim
h1 Add chat room
= form_for @chat_room do |f|
  .form-group
    = f.label :title
    = f.text_field :title, autofocus: true, class: 'form-control'
  = f.submit "Add!", class: 'btn btn-primary'

app/views/chat_rooms/show.html.slim
h1= @chat_room.title
= form_for @message, url: '#' do |f|
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control'
    small.text-muted From 2 to 1000 characters
  = f.submit "Post", class: 'btn btn-primary btn-lg'

#messages data-chat-room-id= "#{@chat_room.id}"
  = render @chat_room.messages

app/views/layouts/_header.html.slim
nav.navbar.navbar-toggleable-md.navbar-light.bg-faded
  button.navbar-toggler.navbar-toggler-right aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  a.navbar-brand href="#{root_path}"  ChitChat
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.ml-auto.move-left
        - if signed_in?
          li.nav-item
            = link_to 'Logout', destroy_user_session_path, class: 'nav-link', method: :delete
        - else
          li.nav-item
            = link_to 'Login', new_user_session_path, class: 'nav-link'
          li.nav-item
            = link_to 'Signup', new_user_registration_path, class: 'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Chitchat
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render partial: 'layouts/header'
    .container
      = yield
    = render partial: 'layouts/footer'

app/views/messages/_message.html.slim
.card
  .card-block
    .row
      .col-md-1
        = gravatar_for message.user
      .col-md-11
        p.card-text
          span.text-muted
            = message.user.name
            at #{message.timestamp} says
          br
          = message.body